default: &default
  oauth2:
    client_id: 796427020393-oarml8asskqpaqp3780rlrfplmvd1aj3.apps.googleusercontent.com
    client_secret: CjPNZ-ID39aP4CJs-y1VCfw0
  cloud_storage:
    bucket: time-tracker-193204
    access_key_id: GOOGUEVJ4L2H3GXMGRYM
    secret_access_key: bEMOoT2LL+bRxppdXdNd86qG4hn2y8fBrcuRYWCy

development:
  <<: *default

production:
  <<: *default
